[15.0][FIX] stock: fix Traceability Report layout
xaviedoanhduy/odoo pull request #4
Opened 2024-12-31 11:07 UTC by xaviedoanhduy

Description of the issue/feature this PR addresses:

Current behavior before PR: 
[stock_traceability.pdf](https://github.com/user-attachments/files/18281023/version-15.0.pdf)

Desired behavior after PR is merged: 
[stock_traceability.pdf](https://github.com/user-attachments/files/18281024/stock_traceability.6.pdf)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2025-01-02 03:33 UTC, nilshamerlinck commented on addons/stock/views/report_stock_traceability.xml
> +            <t t-set="head">
why?

2025-01-02 03:33 UTC, nilshamerlinck commented on addons/stock/__manifest__.py
> +            ('include', 'web.assets_frontend'),
why? does not make sense for a report

2025-01-02 03:36 UTC, nilshamerlinck requested changes
- thanks for the nice description :+1: 
- PRs on stable versions should be as small and innocuous as possible, no refactoring
- if re-introducing `assets_stock_print_report` has too much consequences, the other option might be to add `stock/static/src/scss/stock_traceability_report.scss` to `web.report_assets_common` instead?

2025-01-07 11:53 UTC, xaviedoanhduy commented on addons/stock/__manifest__.py
> +            ('include', 'web.assets_frontend'),
hi @nilshamerlinck, I added other assets included in `stock.assets_stock_print_report` asset because the contents in `stock/static/src/scss/stock_traceability_report.scss` used some .scss variables in the above 2 assets. but you are right adding other assets is wasteful and not much needed for this report.

2025-01-07 11:54 UTC, xaviedoanhduy commented
> * thanks for the nice description 👍
> * PRs on stable versions should be as small and innocuous as possible, no refactoring
> * if re-introducing `assets_stock_print_report` has too much consequences, the other option might be to add `stock/static/src/scss/stock_traceability_report.scss` to `web.report_assets_common` instead?

I changed as per your suggestion, as the` stock.assets_stock_print_report` asset re-introduction seems complicated and wasteful

2025-01-07 11:57 UTC, xaviedoanhduy commented on addons/stock/views/report_stock_traceability.xml
> -            </t>
I don't know why since this commit https://github.com/odoo/odoo/commit/9fadd92 the author has changed as it is now. and this leads to the `<base>` tag never being included in the body (`bodies` is a parameter of the `_run_wkhtmltopdf` function) and leads to incorrect reporting redirect to `base_url`

2025-01-08 10:21 UTC, nilshamerlinck approved these changes
ok, can you update PR description?
pre-approving, let's see what odoo thinks of it

2025-07-24 02:51 UTC, closed without merging